<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>value_spinner_About</name>
   <tag></tag>
   <elementGuidId>f6cb4043-a914-42d5-bcf6-29e2e76b8344</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.option.roboto-medium.ng-scope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='helpMiniTitle']/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>d56df918-e297-46ab-b6d3-2016c0a5991b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option roboto-medium ng-scope</value>
      <webElementGuid>158acd55-6c3d-41af-8e66-c81eac5d85cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>ABOUT</value>
      <webElementGuid>a4d2a373-a496-4de2-ace8-80e1d4fe9a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>mobileRedirectHelp('about')</value>
      <webElementGuid>a39899ef-9635-41c6-a64c-03d8eee52b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>a0d8a016-4c13-48af-96b8-56c854adc90c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>69a387de-28bc-401a-a278-2a51cdb7b80e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>About</value>
      <webElementGuid>c0a37f36-828e-461a-98c6-e53e872ead30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;helpMiniTitle&quot;)/label[@class=&quot;option roboto-medium ng-scope&quot;]</value>
      <webElementGuid>20ce927f-4220-4768-8e88-24446643c8e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='helpMiniTitle']/label</value>
      <webElementGuid>f50c3bc2-d0b2-4b55-8558-e49b2724e17a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Management Console'])[1]/following::label[1]</value>
      <webElementGuid>f03e359c-52d5-447b-a795-b880bf8f7f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AOS Versions'])[1]/following::label[2]</value>
      <webElementGuid>f3554336-d532-4ff2-be6c-40777334e6e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AOS Versions'])[2]/preceding::label[1]</value>
      <webElementGuid>e1cd544a-542d-4333-800b-fc2ed40b3975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Management Console'])[2]/preceding::label[2]</value>
      <webElementGuid>8a49f97d-8a16-456e-a89d-4fa65cfa6807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/label</value>
      <webElementGuid>4dc15f1d-24cb-429c-8baa-0eda7b5e2d4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@href = 'javascript:void(0)' and (text() = 'About' or . = 'About')]</value>
      <webElementGuid>0681bba7-4609-423a-9fa0-a016d736781e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
