<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>value_spinner_AOS Versions</name>
   <tag></tag>
   <elementGuidId>09c47e93-a71e-4dd0-a34a-b0aaca3be8fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='helpMiniTitle']/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>57dcc6a7-7cb9-4fa7-a9f8-0ffdf7d6a58c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option ng-scope</value>
      <webElementGuid>13e5e97c-1a01-4f9b-9225-8045fcf31dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>AOS_VERSIONS</value>
      <webElementGuid>306a132c-3a7b-41b2-a099-9fe154237523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>mobileRedirectHelp('version')</value>
      <webElementGuid>7f1801fc-b5ae-417b-a851-c549ea8bc1a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>0a8638a1-d9eb-40c4-865d-ef14b0e35315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>8fea6325-2b69-43e2-9bd3-54297a69642e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AOS Versions</value>
      <webElementGuid>cd80e17e-85d4-4f11-9c15-2fc05b0d61af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;helpMiniTitle&quot;)/label[@class=&quot;option ng-scope&quot;]</value>
      <webElementGuid>cbd6bd24-d944-45b3-8575-5f3be69fc5dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='helpMiniTitle']/label[2]</value>
      <webElementGuid>483ae77a-9019-4a6e-ad5b-bdfd4a66ecc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[2]/following::label[1]</value>
      <webElementGuid>07a78275-e5b0-459c-ab7d-c64b82378e2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Management Console'])[1]/following::label[2]</value>
      <webElementGuid>15f210be-95e6-41bb-a308-2107a82bbea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Management Console'])[2]/preceding::label[1]</value>
      <webElementGuid>f13594bd-46a6-490a-a46a-16f67d7dba25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/label[2]</value>
      <webElementGuid>40bd228d-0ded-4caf-9c10-f6aca7d4e744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@href = 'javascript:void(0)' and (text() = 'AOS Versions' or . = 'AOS Versions')]</value>
      <webElementGuid>3f7c4244-ec4e-4551-8ae8-e203b9e6f3a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
