<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_EXPLORE NOW_3</name>
   <tag></tag>
   <elementGuidId>ec5597e2-5ab1-457a-8e81-4c133bb54710</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='EXPLORE NOW'])[4]/preceding::button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e5f97163-4707-4290-9d2b-cfeb2f653e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>explore_now_btn</value>
      <webElementGuid>1441dbb6-fc6d-4982-b693-5abfb3baf57d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>redirect('/category/' + categories[img.categoryId].categoryName + '/' + categories[img.categoryId].categoryId)</value>
      <webElementGuid>0b2ac8e7-eb44-4d73-9a28-bc3e34e5eb57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>EXPLORE_NOW</value>
      <webElementGuid>3963bdaf-4f3e-431b-8a1a-f416ddc35eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3db79a55-e1dd-41b1-ad03-f947a9c0dc6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-scope</value>
      <webElementGuid>936de89b-57a1-4a55-be5b-6fbcd6b5c118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EXPLORE NOW</value>
      <webElementGuid>e670b99e-3062-460b-bfa0-69b997da0438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slider_explore_now&quot;)/div[@class=&quot;slider&quot;]/div[@class=&quot;slider-length transition&quot;]/div[@class=&quot;imgSection ng-scope&quot;]/div[@class=&quot;container&quot;]/button[@class=&quot;ng-scope&quot;]</value>
      <webElementGuid>5c84ecb1-3ae6-40b7-af8d-8d873a5a4f6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@name='explore_now_btn'])[3]</value>
      <webElementGuid>053b82b8-f925-422f-9c37-71aad34d6f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='slider_explore_now']/div/div/div[3]/div[2]/button</value>
      <webElementGuid>3e924498-668d-4589-ac15-2c9b61f9bf0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='START EXPLORING HP NOTEBOOKS'])[1]/following::button[1]</value>
      <webElementGuid>dc25ea49-3c57-47ed-8dc7-8a49abf2d8df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXPLORE NOW'])[2]/following::button[1]</value>
      <webElementGuid>b3645cfa-255d-44d5-92e6-8be49518abaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALL YOU WANT FROM A TABLET'])[2]/preceding::button[1]</value>
      <webElementGuid>19573ef2-b95a-4f72-8e9d-47c0df535b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXPLORE NOW'])[4]/preceding::button[1]</value>
      <webElementGuid>2718a8d8-8118-4c5c-89cb-f5749a750478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/button</value>
      <webElementGuid>c3b4b18f-dcf3-4198-aa22-e1a57cf0f51d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'explore_now_btn' and (text() = 'EXPLORE NOW' or . = 'EXPLORE NOW')]</value>
      <webElementGuid>79c47f07-4a05-44b5-96de-f050e690fe06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
