<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_EXPLORE NOW_1</name>
   <tag></tag>
   <elementGuidId>5665c060-2e40-4fd0-8c74-5fb76010d686</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;explore_now_btn&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='SEE OFFER'])[1]/following::button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bf6804bb-8ee7-4cfd-a5d9-7fe84260f40a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>explore_now_btn</value>
      <webElementGuid>dfd71eac-0df7-4429-ade6-40b74a989c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>redirect('/category/' + categories[img.categoryId].categoryName + '/' + categories[img.categoryId].categoryId)</value>
      <webElementGuid>51b89f98-ecf9-4e9c-997b-a84c4069fb94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>EXPLORE_NOW</value>
      <webElementGuid>a10f6891-8899-46d8-adef-f5f866032d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>900bb75a-1c7d-4aa8-9a69-2ea672eaf21d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-scope</value>
      <webElementGuid>72c8c69c-ebcb-4f41-8477-67679c7d1743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EXPLORE NOW</value>
      <webElementGuid>8eeaa422-231c-4c5c-a7cf-6f851a4ae7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slider_explore_now&quot;)/div[@class=&quot;slider&quot;]/div[@class=&quot;slider-length transition&quot;]/div[@class=&quot;imgSection ng-scope&quot;]/div[@class=&quot;container&quot;]/button[@class=&quot;ng-scope&quot;]</value>
      <webElementGuid>451d9e7f-b471-4678-b3ef-ca5c14514b73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='explore_now_btn']</value>
      <webElementGuid>2f61da10-094b-4071-94f8-e16a4edf552e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='slider_explore_now']/div/div/div/div[2]/button</value>
      <webElementGuid>c86490c6-c97e-4141-acd5-e8d39b795152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALL YOU WANT FROM A TABLET'])[1]/following::button[1]</value>
      <webElementGuid>3885c573-7a9d-4c99-8761-c1f5366490bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEE OFFER'])[1]/following::button[1]</value>
      <webElementGuid>964557f5-ab36-4957-a3c8-4551bb685d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXPLORE NOW'])[2]/preceding::button[1]</value>
      <webElementGuid>c6ddc175-61aa-47c2-96f4-250c23ee9429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>b579144b-d617-44dc-9469-affd04dee304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'explore_now_btn' and (text() = 'EXPLORE NOW' or . = 'EXPLORE NOW')]</value>
      <webElementGuid>8131b7e3-20c7-49a9-9a33-dbea193cc691</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
