<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_View Details_1</name>
   <tag></tag>
   <elementGuidId>fe1a4816-22b1-4852-8349-1f9d0e876ac9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#details_21</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='View Details'])[2]/following::label[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a3c2206c-9d1e-403f-8d1a-7cee3521cd5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>details_21</value>
      <webElementGuid>6f5dfcfa-805c-4795-a57a-5abfec007274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shop_nowSub viewDetail ng-scope</value>
      <webElementGuid>ce117532-9f7a-4ac7-b6b9-9ad71bdfb86c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>View_details</value>
      <webElementGuid>2622e029-86db-4457-ba73-630ac720e7f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Details</value>
      <webElementGuid>b9318314-7d94-48b1-8062-20f042d91852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;details_21&quot;)</value>
      <webElementGuid>dfc34448-7393-4243-a5bb-201cb70d9920</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='details_21']</value>
      <webElementGuid>deb3d616-8325-4c85-ba67-e5e358ee5235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='popular_items']/div/div[3]/a/label</value>
      <webElementGuid>b034e5f6-6c6b-40e2-8888-20002b30ff8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Details'])[2]/following::label[1]</value>
      <webElementGuid>83980708-b25b-42e3-a39b-60fc735a6c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Details'])[1]/following::label[2]</value>
      <webElementGuid>813c00a7-726a-443f-bede-d5dd6a09db60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHAT WITH US'])[1]/preceding::label[1]</value>
      <webElementGuid>01484234-2b2e-43c2-95e4-f2f26ca5e299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTACT US'])[2]/preceding::label[2]</value>
      <webElementGuid>5bcfc278-60ee-4b26-999e-36965ee25079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/label</value>
      <webElementGuid>ca0c1a4b-31c8-4084-9205-435700ca905b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'details_21' and (text() = 'View Details' or . = 'View Details')]</value>
      <webElementGuid>d25e3d07-a076-43b5-9e51-673be860445b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
