<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_View Details_2</name>
   <tag></tag>
   <elementGuidId>04a88802-1c3c-46b0-8e0f-dacfade3bf5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#details_10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='View Details'])[1]/following::label[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>14169167-bd59-4d0b-8a19-07b3776d96a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>details_10</value>
      <webElementGuid>606846fb-7e72-4de3-8ac1-c6a1b513b082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shop_nowSub viewDetail ng-scope</value>
      <webElementGuid>6c42161a-9943-4079-8425-80859b1e18d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>View_details</value>
      <webElementGuid>c1a0a534-e3c8-4284-88f2-f2d0872a0588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Details</value>
      <webElementGuid>6c2550bf-0d86-4ca4-8aee-4d37feb1f3e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;details_10&quot;)</value>
      <webElementGuid>577a5354-3d4a-4ceb-b122-60e64cbc5684</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='details_10']</value>
      <webElementGuid>17492118-7bdb-44b9-9b62-434041d22985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='popular_items']/div/div[2]/a/label</value>
      <webElementGuid>a808729b-ebc1-4d83-b13e-3927cd0b89cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Details'])[1]/following::label[1]</value>
      <webElementGuid>d34a1e96-e75d-4350-b197-0c80255184c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POPULAR ITEMS'])[2]/following::label[2]</value>
      <webElementGuid>ed42bab0-39b8-4636-b159-f70eef949257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Details'])[3]/preceding::label[1]</value>
      <webElementGuid>1e0f973e-fff5-48ff-b803-6fda9cb6a1e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHAT WITH US'])[1]/preceding::label[2]</value>
      <webElementGuid>1dd9d9c5-557c-4e42-9b65-92c0d0ba605f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/label</value>
      <webElementGuid>8b5c980a-7de6-4733-bf27-01c29d257604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'details_10' and (text() = 'View Details' or . = 'View Details')]</value>
      <webElementGuid>28c72928-4bee-4e74-acb1-4470830140bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
