<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_product_3</name>
   <tag></tag>
   <elementGuidId>27204d61-52cf-4a4b-bfc5-181e58a17ea1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[name=&quot;popular_item_21_img&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='popular_items']/div/div[3]/figure/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7d7d3287-5079-4f62-9740-d65c637d4997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>popular_item_21_img</value>
      <webElementGuid>f473103f-983f-4b4f-bab9-61fa58045618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-src</name>
      <type>Main</type>
      <value>css/images/Popular-item1.jpg</value>
      <webElementGuid>de05c943-df4a-4f17-a57f-207357868504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Special-offer</value>
      <webElementGuid>2acbba1e-9058-484d-b512-7b02ce83680e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>6ac1cb02-6e8c-4190-9954-4904b14a02ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>68b8d2cb-d5b2-4d65-9f06-bffb777969a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>css/images/Popular-item1.jpg</value>
      <webElementGuid>e424e083-b09b-479d-8940-1aabc73fef49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popular_items&quot;)/div[@class=&quot;grid-table center&quot;]/div[@class=&quot;ng-scope&quot;]/figure[1]/img[1]</value>
      <webElementGuid>76de346f-2c5b-4593-8cf7-627866047f23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@name='popular_item_21_img']</value>
      <webElementGuid>e523bcd6-644f-4633-bf87-eee27d68f24f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='popular_items']/div/div[3]/figure/img</value>
      <webElementGuid>2c6303d4-5bfe-4d5f-97d3-19038f5c47f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Details'])[2]/following::img[1]</value>
      <webElementGuid>4820cfcd-2e50-4333-a6bb-2f291b11ac9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Details'])[1]/following::img[2]</value>
      <webElementGuid>460a30b5-1d94-4b81-b2b0-0b097c2d3903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Details'])[3]/preceding::img[1]</value>
      <webElementGuid>85109066-d5b4-4d6a-8dee-d4c375847c82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHAT WITH US'])[1]/preceding::img[2]</value>
      <webElementGuid>e2726d97-b278-4b60-a52d-a4accb9bc873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Special-offer'])[4]</value>
      <webElementGuid>bb7acf1e-935e-4dfa-8a74-92692fcc534b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/figure/img</value>
      <webElementGuid>2abc4ad2-6820-4a17-9eb9-a5a738bfb14c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@name = 'popular_item_21_img' and @alt = 'Special-offer' and @href = 'javascript:void(0)' and @src = 'css/images/Popular-item1.jpg']</value>
      <webElementGuid>aeb3e078-ea17-49e7-8580-91c04c52eaf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
