<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_TABLETS</name>
   <tag></tag>
   <elementGuidId>d76a2f45-9469-482d-b115-9ca5f9e569d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tabletsTxt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='tabletsTxt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ce30aa55-7d61-4c1a-97f2-77a9a5f6c507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tabletsTxt</value>
      <webElementGuid>c9396a0c-ea72-47e8-9a47-648e6a8898f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>TabletsCategoryTxt</value>
      <webElementGuid>7668b68e-e2cc-44a5-9d62-6cc9501d5492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shop_now roboto-bold ng-binding</value>
      <webElementGuid>1592377a-0a33-4281-a5d0-10645b5b340d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>88c0fb10-f02e-4607-9c72-226547f44db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>4525f13f-ba02-4d20-a5bd-17e251d39705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TABLETS</value>
      <webElementGuid>3db04243-5cde-440f-a4a6-dd38f21d5e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabletsTxt&quot;)</value>
      <webElementGuid>d357439a-82e1-4530-bb1a-79646a8d768c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='tabletsTxt']</value>
      <webElementGuid>b46eb4c3-d3b0-4d72-ba0e-ecee882881cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabletsImg']/div/span</value>
      <webElementGuid>e79a601c-78a3-4811-b779-d310de0aa347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop Now'])[1]/following::span[1]</value>
      <webElementGuid>9b1ca245-8a0a-4a4f-bde9-067799942c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SPEAKERS'])[1]/following::span[1]</value>
      <webElementGuid>20a59990-54c4-49c8-b4b6-666d7f980ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop Now'])[2]/preceding::span[1]</value>
      <webElementGuid>5d1cad67-cca4-4066-9313-712ff5849eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LAPTOPS'])[1]/preceding::span[1]</value>
      <webElementGuid>98381d9d-6867-4ef3-ac43-710ca09013a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span</value>
      <webElementGuid>111172a9-44c3-4eee-85dc-4e898520c70b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'tabletsTxt' and @href = 'javascript:void(0)' and (text() = 'TABLETS' or . = 'TABLETS')]</value>
      <webElementGuid>e97d74ec-f0a3-4db7-8b43-bba54678aecb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
