<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_quantity_min</name>
   <tag></tag>
   <elementGuidId>38a0ec6e-4785-4601-8836-19cd88b30487</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.minus.disableBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='productProperties']/div[2]/e-sec-plus-minus/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c2cf1b15-3c48-4935-8bc2-64c65938eebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>minus disableBtn</value>
      <webElementGuid>624485e0-0dc0-4571-9eb9-a70e1cf42f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>increment-value-attr</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>e0d6846d-ae5e-4a04-8cb3-51f02bc520f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productProperties&quot;)/div[@class=&quot;smoolMargin&quot;]/e-sec-plus-minus[@class=&quot;ng-isolate-scope sec-plus-minus&quot;]/div[@class=&quot;e-sec-plus-minus&quot;]/div[@class=&quot;minus disableBtn&quot;]</value>
      <webElementGuid>aae9a70f-b496-4713-95f5-92324e8f8177</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='productProperties']/div[2]/e-sec-plus-minus/div/div</value>
      <webElementGuid>315759b6-d128-4693-b899-e0312315fcd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity:'])[1]/following::div[2]</value>
      <webElementGuid>84c0c201-cacd-4b0e-9873-840af8927970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color:'])[1]/following::div[5]</value>
      <webElementGuid>7e3ec858-24dd-4b74-b4ee-088ee6ac2e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Warranty'])[1]/preceding::div[3]</value>
      <webElementGuid>ae0dc458-bd59-4b88-8875-40499a499590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$100.00'])[1]/preceding::div[3]</value>
      <webElementGuid>e58ef6e0-4fe2-4494-bdd5-048bcc620c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//e-sec-plus-minus/div/div</value>
      <webElementGuid>1463d06c-f0ac-431d-9b51-e396b69979a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
