<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_product</name>
   <tag></tag>
   <elementGuidId>976c44a4-4dd3-4f06-80ff-25e27fa7a608</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mainImg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//figure/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e7a3a774-ff67-4bdf-bffa-c6a36b583fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainImg</value>
      <webElementGuid>06c8ff2b-414d-4964-9877-336badd463d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-src</name>
      <type>Main</type>
      <value>/catalog/fetchImage?image_id=4200</value>
      <webElementGuid>4a40449f-4609-4d2c-b9f5-4c4100228a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/catalog/fetchImage?image_id=4200</value>
      <webElementGuid>ade9bd71-18ef-4513-aed8-af062cf0197f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainImg&quot;)</value>
      <webElementGuid>59c32ceb-4bb3-49ce-87ae-7fc174338c6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='mainImg']</value>
      <webElementGuid>73c3e4df-0d09-49a3-a6c0-61ded6fb9c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-section']/figure/img</value>
      <webElementGuid>b361db35-bd32-4b8c-9bcb-d76a7f69ccd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOLD OUT'])[1]/following::img[1]</value>
      <webElementGuid>555952b0-fef2-448d-93a1-04cd8b02889e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BOSE SOUNDLINK BLUETOOTH SPEAKER III'])[3]/preceding::img[2]</value>
      <webElementGuid>f565cb39-6f3b-4644-8877-ef05aff3a5c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/img</value>
      <webElementGuid>774860e1-8046-44d6-9a17-4cc34708fd8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'mainImg' and @src = '/catalog/fetchImage?image_id=4200']</value>
      <webElementGuid>9357e406-f125-4a89-a609-49fa78982634</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
