<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_desc product</name>
   <tag></tag>
   <elementGuidId>ff7a8507-3052-4605-98ff-cd1efdca5d2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.roboto-light.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Description']/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>72c601db-6b2d-47c4-ac96-91f7b1bd4476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-light ng-binding</value>
      <webElementGuid>eede5ed2-d440-4fa8-8e7c-b261190a64eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Meet the speaker that brings your music and friends together-with a style that's all your own. The SoundLink® Bluetooth speaker III is our best-performing mobile Bluetooth speaker. It plays louder and longer than its popular predecessor, with advanced Bose® technologies that reproduce the fullness, clarity and depth of your music. And a colorful assortment of optional covers let you personalize your speaker. </value>
      <webElementGuid>63ccee78-b625-4eb3-b57c-69b903cd77c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Description&quot;)/p[@class=&quot;roboto-light ng-binding&quot;]</value>
      <webElementGuid>b8f0c27d-dc3e-4938-9c33-a1260570f96e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Description']/p</value>
      <webElementGuid>6523a2fb-d0af-4998-9147-b920f16c31fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOLD OUT'])[2]/following::p[1]</value>
      <webElementGuid>734b6969-a94e-4cae-8c2e-ae4920642ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color:'])[1]/preceding::p[1]</value>
      <webElementGuid>1e406b11-147d-401d-b862-db58f3146a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity:'])[1]/preceding::p[1]</value>
      <webElementGuid>b60d68ae-1bc7-4ca7-b5d0-747475b3543b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>3e296d43-7ca0-401b-9f02-c857cbe5885e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = concat(&quot; Meet the speaker that brings your music and friends together-with a style that&quot; , &quot;'&quot; , &quot;s all your own. The SoundLink® Bluetooth speaker III is our best-performing mobile Bluetooth speaker. It plays louder and longer than its popular predecessor, with advanced Bose® technologies that reproduce the fullness, clarity and depth of your music. And a colorful assortment of optional covers let you personalize your speaker. &quot;) or . = concat(&quot; Meet the speaker that brings your music and friends together-with a style that&quot; , &quot;'&quot; , &quot;s all your own. The SoundLink® Bluetooth speaker III is our best-performing mobile Bluetooth speaker. It plays louder and longer than its popular predecessor, with advanced Bose® technologies that reproduce the fullness, clarity and depth of your music. And a colorful assortment of optional covers let you personalize your speaker. &quot;))]</value>
      <webElementGuid>5795c516-b026-4851-9f3e-f240769dc80b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
