<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_name product</name>
   <tag></tag>
   <elementGuidId>b6605a47-f596-4598-9446-d6b56d2f971a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.roboto-regular.screen768.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Description']/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>303fbc72-0ef0-4b21-ad71-5f9a154212c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-regular screen768 ng-binding</value>
      <webElementGuid>18fca340-d864-4d90-8eca-830f7506c66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> BOSE SOUNDLINK BLUETOOTH SPEAKER III </value>
      <webElementGuid>25f7944c-6e5f-4ee3-9ae1-77f7fa10ea32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Description&quot;)/h1[@class=&quot;roboto-regular screen768 ng-binding&quot;]</value>
      <webElementGuid>6ddf46fe-235e-4082-b2b4-a5b499d5b9e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Description']/h1</value>
      <webElementGuid>d3578e24-1e3c-4d1e-bf0f-fda1904a8fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOLD OUT'])[1]/following::h1[1]</value>
      <webElementGuid>2a8281fa-95e3-4414-b61d-9bc10605da1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOLD OUT'])[2]/preceding::h1[1]</value>
      <webElementGuid>98995cea-f2af-474f-b3ee-7f972b3c17bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h1</value>
      <webElementGuid>bd3ac98d-4657-4129-957f-095a1ee197b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = ' BOSE SOUNDLINK BLUETOOTH SPEAKER III ' or . = ' BOSE SOUNDLINK BLUETOOTH SPEAKER III ')]</value>
      <webElementGuid>0b84e074-9cf8-471b-bc0c-c85037df094e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
