<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_twitter</name>
   <tag></tag>
   <elementGuidId>800d7a2f-7c89-44a0-a469-d04e3e3883cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[name=&quot;follow_twitter&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@name='follow_twitter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>73bc8e35-d8b8-40b0-914d-70f9f93e2b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>follow_twitter</value>
      <webElementGuid>fe0060b8-0d15-4a1c-bf75-c4f19eeac5ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>css/images/twitter.png</value>
      <webElementGuid>c095e593-1b93-4c5e-9490-9c86bfda384e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>87a8642b-5c03-4264-87af-1009f8c34eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;follow&quot;)/a[2]/img[1]</value>
      <webElementGuid>ec405fd7-8e24-41a9-8983-97f33a0fa0e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@name='follow_twitter']</value>
      <webElementGuid>d2d85e4d-757a-4f0a-b7a2-1e82340b1e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='follow']/a[2]/img</value>
      <webElementGuid>b467938a-8b9f-40b6-acaa-e9c0aebdd4d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FOLLOW US'])[1]/following::img[2]</value>
      <webElementGuid>073e8d60-4ce6-4a24-8fb0-0e5f5e366801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTINUE SHOPPING'])[1]/following::img[2]</value>
      <webElementGuid>09529908-49a0-43d7-9d51-df7dd9d1fa97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© Advantage Inc, 2021. Release 3.2'])[1]/preceding::img[2]</value>
      <webElementGuid>9597fc26-a460-4f4b-a3a8-52837fb29f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Added Successfully'])[1]/preceding::img[2]</value>
      <webElementGuid>289993ce-6768-4b8f-82e3-29650c80d5fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='icon'])[2]</value>
      <webElementGuid>84252aab-32da-43ed-a205-cc0e904cb123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/img</value>
      <webElementGuid>fef55956-a420-4403-a4a3-fbe66f5e0d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@name = 'follow_twitter' and @src = 'css/images/twitter.png' and @alt = 'icon']</value>
      <webElementGuid>3f79c64a-d63a-4b83-8088-d4c2355a93b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
