<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_CREATE ACCOUNT title (2)</name>
   <tag></tag>
   <elementGuidId>b28cdf27-c2eb-4d61-a01b-10006b8ea88b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.roboto-regular.sticky.fixedImportant.ng-scope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='registerPage']/article/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>1b14b4ce-77c6-4855-9a59-7699e5da994d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-regular sticky fixedImportant ng-scope</value>
      <webElementGuid>ced4b3e9-e9c0-4b0f-91e3-1cd6ca37a970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>CREATE_ACCOUNT</value>
      <webElementGuid>df6d6576-c4e6-40a4-9784-f4938300aee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CREATE ACCOUNT</value>
      <webElementGuid>b12f5c81-ee6d-451f-a99b-ad577f510a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerPage&quot;)/article[1]/h3[@class=&quot;roboto-regular sticky fixedImportant ng-scope&quot;]</value>
      <webElementGuid>ae63a2a6-7bbd-430a-acdf-2053d93dcc22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='registerPage']/article/h3</value>
      <webElementGuid>5a995efd-2105-49d5-bfa9-0f8bb5a09ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CREATE ACCOUNT'])[1]/following::h3[1]</value>
      <webElementGuid>1e44fa8f-45ac-4e63-a8af-5d52f23bc4b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HOME'])[1]/following::h3[1]</value>
      <webElementGuid>ea42c6e1-8969-4785-ac84-f27b745393d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOTICE'])[1]/preceding::h3[1]</value>
      <webElementGuid>cf0b7d2e-c066-4696-9d54-05c54f20218b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACCOUNT DETAILS'])[1]/preceding::h3[1]</value>
      <webElementGuid>84923b15-0878-4091-b31f-1ebe37fa47ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/h3</value>
      <webElementGuid>10eece24-4289-4a71-8177-42dd79cfd62b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'CREATE ACCOUNT' or . = 'CREATE ACCOUNT')]</value>
      <webElementGuid>da285cfb-9684-4ad8-8531-eb6941e2cd8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
