<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_info field</name>
   <tag></tag>
   <elementGuidId>d6b93c2e-a3cc-422f-b27d-163b5e3bc2a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>info-demo.info-demo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='infoDemo']/info-demo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>info-demo</value>
      <webElementGuid>1ed6fd2c-a966-4460-9494-5ced381cccb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>a-title</name>
      <type>Main</type>
      <value>NOTICE</value>
      <webElementGuid>38d1fa1a-51eb-4a47-bb72-a4ccddc694d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>a-lines</name>
      <type>Main</type>
      <value>[&quot;This is a demo site.&quot;,&quot;Do not use real data.&quot;]</value>
      <webElementGuid>cc0d43ac-6523-4425-af0d-dee6d36999e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>info-demo</value>
      <webElementGuid>fdf852a9-54a4-4beb-8313-d66053aac37f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NOTICEThis is a demo site.Do not use real data.</value>
      <webElementGuid>5ec34c7b-0915-410d-ae53-193c8ac3a938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;infoDemo&quot;)/info-demo[@class=&quot;info-demo&quot;]</value>
      <webElementGuid>80b4ef07-3ed3-46fa-b872-0359ec18cd45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='infoDemo']/info-demo</value>
      <webElementGuid>d23df4aa-6572-4316-90d3-018f590fd618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CREATE ACCOUNT'])[2]/following::info-demo[1]</value>
      <webElementGuid>7eac2f28-266d-4782-818c-a3753b802ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CREATE ACCOUNT'])[1]/following::info-demo[1]</value>
      <webElementGuid>d8ed9a86-a3c3-487d-9acc-f91d2aab6b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACCOUNT DETAILS'])[1]/preceding::info-demo[1]</value>
      <webElementGuid>9a2a719c-4998-4d1d-98c1-ecfc5c8eae18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//info-demo</value>
      <webElementGuid>178441ff-90cc-4bc2-832d-cbdfdfbba405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//info-demo[(text() = 'NOTICEThis is a demo site.Do not use real data.' or . = 'NOTICEThis is a demo site.Do not use real data.')]</value>
      <webElementGuid>0f5462bd-be12-4d82-8726-92bf24efd006</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
