<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_LAPTOPS</name>
   <tag></tag>
   <elementGuidId>cd8f24d2-0fae-411d-95ee-4fe27f148d4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#laptopsTxt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='laptopsTxt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f78295a6-825d-418b-8aac-20189c10fb43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>laptopsTxt</value>
      <webElementGuid>6610ae4c-3478-42b0-92eb-49383e5e4876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>LaptopsCategoryTxt</value>
      <webElementGuid>66753810-2335-4a6e-bb43-1471c91f8f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shop_now roboto-bold ng-binding</value>
      <webElementGuid>c04137cb-99d4-4b7d-91e2-70f44221808e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>322c630e-7d86-428e-85ee-5b60a420dc1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>cd10c728-284e-4482-9e95-4a79b63b63be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LAPTOPS</value>
      <webElementGuid>a5ad2d02-2236-47bc-b946-ac7319ad2b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;laptopsTxt&quot;)</value>
      <webElementGuid>e60e6bdf-8b06-4359-9f48-a295e94ae4fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='laptopsTxt']</value>
      <webElementGuid>c8ad4f7c-72ec-48d9-9d52-702c17df6c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='laptopsImg']/div/span</value>
      <webElementGuid>cd645795-c2c1-4d35-a68e-0e479f12574b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop Now'])[2]/following::span[1]</value>
      <webElementGuid>63094a4c-0a6c-476d-bde1-1a7daf0bc292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TABLETS'])[1]/following::span[1]</value>
      <webElementGuid>126e492b-8276-4766-965e-63eb3fefb143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop Now'])[3]/preceding::span[1]</value>
      <webElementGuid>dad7fe83-ba4e-4fd2-ac7e-f3da58532752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MICE'])[1]/preceding::span[1]</value>
      <webElementGuid>bf89b34c-36bd-4d96-97ba-d6b06e0a6f4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span</value>
      <webElementGuid>9073c9e2-f07d-4855-a972-c28b6bef1c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'laptopsTxt' and @href = 'javascript:void(0)' and (text() = 'LAPTOPS' or . = 'LAPTOPS')]</value>
      <webElementGuid>9e50c97d-b690-4f97-8b49-353658b85b79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
