<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_HEADPHONES</name>
   <tag></tag>
   <elementGuidId>8ff43c7b-736c-40f0-a6cb-306ed82270bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#headphonesTxt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='headphonesTxt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b69d1769-7646-4c17-ac4a-dbe5923850ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headphonesTxt</value>
      <webElementGuid>e3dfcc9c-3611-4020-baa4-66a62bc36d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>HeadphonesCategoryTxt</value>
      <webElementGuid>5101437b-1ae5-4232-bebd-f70eda83124c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shop_now roboto-bold ng-binding</value>
      <webElementGuid>3280e7d5-61ab-4127-a5c3-0280b14a1e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>0d9af55d-4019-454a-b5c7-e2d4a562f5bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>d563590b-8d96-47d6-b8be-be9deac4feaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HEADPHONES</value>
      <webElementGuid>506f16b7-8ac2-4612-b03f-ac512273dab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headphonesTxt&quot;)</value>
      <webElementGuid>4d274294-5c94-458b-a7ca-38f2a96adb2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='headphonesTxt']</value>
      <webElementGuid>71f9ecbd-1126-4b8e-901c-228f728239b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headphonesImg']/div/span</value>
      <webElementGuid>124ee402-9100-4872-bc64-314ad599e6f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop Now'])[4]/following::span[1]</value>
      <webElementGuid>1dd6135c-0c29-4e85-8a4a-4e0b4bd5e72d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MICE'])[1]/following::span[1]</value>
      <webElementGuid>6e2cf725-753a-4d19-b69c-062e24904491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop Now'])[5]/preceding::span[1]</value>
      <webElementGuid>692e735b-ee6c-4623-9eb2-ad083bf0b9c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SPECIAL OFFER'])[2]/preceding::span[1]</value>
      <webElementGuid>562b9b6c-08a0-463b-9e7a-5a188f034885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span</value>
      <webElementGuid>e00ca434-8150-4734-acf3-c352e02a8715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'headphonesTxt' and @href = 'javascript:void(0)' and (text() = 'HEADPHONES' or . = 'HEADPHONES')]</value>
      <webElementGuid>aea7530a-5fa0-459c-a442-f0169a6e4329</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
