<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_MICE</name>
   <tag></tag>
   <elementGuidId>c27628f8-ed9b-4784-97b3-3e4a3a4b6108</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#miceTxt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='miceTxt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b94f8a0e-3328-4246-b7d5-43c0c6a99fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>miceTxt</value>
      <webElementGuid>b073a8ff-81b5-410c-89c4-8b3f3a41fe95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>MiceCategoryTxt</value>
      <webElementGuid>afee77d9-47cc-4304-8d24-830fa9a58b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shop_now roboto-bold ng-binding</value>
      <webElementGuid>ece2e87b-32bb-4603-8b80-d62b7d72eebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>10348a83-3b81-44d7-9d53-dd469209fded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>cc20ff33-92c1-44a2-b361-d5878cdaaaeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MICE</value>
      <webElementGuid>24114154-4c8c-4639-be75-70c125011a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;miceTxt&quot;)</value>
      <webElementGuid>7a042e4d-9fdb-4942-a91a-e926cd784a7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='miceTxt']</value>
      <webElementGuid>1ecddb5c-a94b-4f6d-8a6d-9a3eeb8dde16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='miceImg']/div/span</value>
      <webElementGuid>1679146c-06ab-448f-b7bf-0d5dd296a803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop Now'])[3]/following::span[1]</value>
      <webElementGuid>d6575901-9a2e-46d7-ac7f-4ed68160ea3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LAPTOPS'])[1]/following::span[1]</value>
      <webElementGuid>7c4f9cc5-748c-43e4-aebf-5da6442d5cc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop Now'])[4]/preceding::span[1]</value>
      <webElementGuid>4ad05b3a-7748-4770-bf27-69feb1c67595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HEADPHONES'])[1]/preceding::span[1]</value>
      <webElementGuid>8e841475-0f9e-42a8-bce6-ff0e34ba3254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/span</value>
      <webElementGuid>b27581a1-eaef-4ede-b76b-8ec1a8ebfaeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'miceTxt' and @href = 'javascript:void(0)' and (text() = 'MICE' or . = 'MICE')]</value>
      <webElementGuid>69c3c953-a5f1-4353-a256-05e218713ca3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
