<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_name product_2</name>
   <tag></tag>
   <elementGuidId>04cabed1-7d12-4c11-9b12-093089ed7d9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p[name=&quot;popular_item_10_name&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='popular_items']/div/div[2]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>7ba70e9a-dbe6-4beb-8e42-70b10d24235e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>popular_item_10_name</value>
      <webElementGuid>84b0ea19-212b-485e-98e9-fc3e6af71e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>center productName roboto-medium ng-binding</value>
      <webElementGuid>f887f1e7-f75e-4ef6-baa9-58ef5fbc8688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HP ELITEBOOK FOLIO</value>
      <webElementGuid>fc0f105d-416e-437d-878a-c119a60a62bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popular_items&quot;)/div[@class=&quot;grid-table center&quot;]/div[@class=&quot;ng-scope&quot;]/p[@class=&quot;center productName roboto-medium ng-binding&quot;]</value>
      <webElementGuid>fa12561d-2035-43bc-a333-029b60cfcd81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@name='popular_item_10_name']</value>
      <webElementGuid>a33daa3f-577a-402b-b282-f64438f648e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='popular_items']/div/div[2]/p</value>
      <webElementGuid>ccc7a951-2c2a-4d10-ab11-72e4eb638c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Details'])[1]/following::p[1]</value>
      <webElementGuid>1c630566-e22f-4bc2-aed2-3f4430be0e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POPULAR ITEMS'])[2]/following::p[2]</value>
      <webElementGuid>8bd9bce0-0827-46e1-9ce8-d98e3d3cef8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Details'])[2]/preceding::p[1]</value>
      <webElementGuid>d7d5f108-55c5-4881-a272-4c27df6c280e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Details'])[3]/preceding::p[2]</value>
      <webElementGuid>394afd66-0de2-4a8f-9c24-434ef3c0dfec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>a2a5cb5d-3c76-4f9c-bcf0-38e9ed6b25df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@name = 'popular_item_10_name' and (text() = 'HP ELITEBOOK FOLIO' or . = 'HP ELITEBOOK FOLIO')]</value>
      <webElementGuid>5e15bcfe-df92-4c96-9be2-ef530b1dbb5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
