<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>44494d06-280b-401b-ac40-163a75e09056</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#helpLink > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='helpLink']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9ee2e5b6-a55b-40e0-9556-870c47100932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../css/images/Down_arrow.svg</value>
      <webElementGuid>bc191a41-c715-4c83-8acc-ee174117c5c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>12px</value>
      <webElementGuid>ea3caece-6aa7-4175-867b-598af98cfe2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>7px</value>
      <webElementGuid>9dbbda2b-f9c1-498d-8caf-79fd09d4b8c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;helpLink&quot;)/img[1]</value>
      <webElementGuid>9c1b3e7b-1de1-463d-aab3-a023fc9aeb8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='helpLink']/img</value>
      <webElementGuid>aa294c9d-a7a3-42e4-a953-dc7c05af280a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Management Console'])[1]/following::img[1]</value>
      <webElementGuid>a4b2be19-a58e-4eec-b3ed-0aef5100b883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AOS Versions'])[1]/following::img[1]</value>
      <webElementGuid>94e8915a-cacd-4cd7-ac59-724b50956d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[2]/preceding::img[1]</value>
      <webElementGuid>bf1f043a-b6b2-41bc-83fa-7bf8eeed8d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AOS Versions'])[2]/preceding::img[1]</value>
      <webElementGuid>f14a2192-737c-4683-a06f-f3540ef37007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>fac0d483-b419-4b5c-9505-98b80c7cf6e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../css/images/Down_arrow.svg']</value>
      <webElementGuid>3f2aafe4-ef5d-41d1-994e-4fd5a038e4ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
