<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_SEE OFFER</name>
   <tag></tag>
   <elementGuidId>e61ce259-7e8c-4ec7-b22a-c664ff677523</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#see_offer_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='see_offer_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>74d0d317-ab94-479b-b18c-2ecb348959e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>see_offer_btn</value>
      <webElementGuid>eeaa63ee-94bd-485d-81cc-d7ca6ee1bd91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>SEE_OFFER</value>
      <webElementGuid>76eaa9ac-bb19-475b-a7a4-f73125c8a41d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f72b9af2-0059-46fb-a28c-a238822c63e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-scope</value>
      <webElementGuid>bb3c05f6-dd7b-49e0-8d2b-a0c830efb4a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEE OFFER</value>
      <webElementGuid>e4f712f4-9276-418e-9c93-37fb9bbbaa89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;see_offer_btn&quot;)</value>
      <webElementGuid>051ef475-85d6-4701-ba43-64ec62dda281</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='see_offer_btn']</value>
      <webElementGuid>9993bd7b-6be1-4888-8a05-aada88f62234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-special-offer']/div/a/button</value>
      <webElementGuid>5cfa2981-1003-4dbb-b380-479a6a2e1c9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HP Pavilion 15z Touch Laptop'])[1]/following::button[1]</value>
      <webElementGuid>f6c9eb4d-7aeb-49ee-9328-6c01ea599fe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXPLORE THE NEW DESIGN'])[1]/following::button[1]</value>
      <webElementGuid>e1070294-d92d-4792-992f-6ba6360cef13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALL YOU WANT FROM A TABLET'])[1]/preceding::button[1]</value>
      <webElementGuid>77f8d053-e051-4020-a7d3-95e87b3ff4eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXPLORE NOW'])[1]/preceding::button[1]</value>
      <webElementGuid>65746027-74a4-4ab9-9746-6547a7b89d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/button</value>
      <webElementGuid>d8b7b0c5-1afa-44f8-930e-d55341b6ada9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'see_offer_btn' and (text() = 'SEE OFFER' or . = 'SEE OFFER')]</value>
      <webElementGuid>e13b4377-8c9e-4695-92f8-e7d3ea8518f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
