<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_SPECIAL OFFER</name>
   <tag></tag>
   <elementGuidId>ef9c5cfd-9263-4023-a2ba-c41491c3a77f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.roboto-regular.center.ng-scope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='special_offer_items']/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>d68a1b2f-df5a-49df-ab35-37e2a26ca539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-regular center ng-scope</value>
      <webElementGuid>28665454-8260-4249-aa50-be37f628e54b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>SPACIAL_OFFER</value>
      <webElementGuid>8f668de4-32ac-49b7-a326-e5dd59acecef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SPECIAL OFFER</value>
      <webElementGuid>6436c391-7be6-4c06-9aef-c94fcb0c678a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;special_offer_items&quot;)/h3[@class=&quot;roboto-regular center ng-scope&quot;]</value>
      <webElementGuid>640e9850-5da0-4d73-82e1-f8e7807395d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='special_offer_items']/h3</value>
      <webElementGuid>ffea4461-e325-4e0b-9d27-82ac5e1fa523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop Now'])[5]/following::h3[1]</value>
      <webElementGuid>097be25f-c28f-45ed-b1cf-4808aec1634b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HEADPHONES'])[1]/following::h3[1]</value>
      <webElementGuid>536ce93b-a2ae-4dd2-b4d4-e6809dabfa37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXPLORE THE NEW DESIGN'])[1]/preceding::h3[1]</value>
      <webElementGuid>dcb6e135-1308-42f0-a851-f83bdf1a1627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HP Pavilion 15z Touch Laptop'])[1]/preceding::h3[1]</value>
      <webElementGuid>11a03646-83a9-466b-ae13-b6c542969112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[2]/h3</value>
      <webElementGuid>4463a2c8-9f7f-45c8-a8a7-70007b860310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'SPECIAL OFFER' or . = 'SPECIAL OFFER')]</value>
      <webElementGuid>afff37fb-d203-4451-8a62-b59c5b4ae72d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
