<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_product</name>
   <tag></tag>
   <elementGuidId>c53cc690-c4ab-40c5-8bac-cb7360cdc4c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Special-offer&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='img-special-offer']/figure/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e63d0f84-f168-4bec-bf2c-f631f2b8e3b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>css/images/Special-offer.jpg</value>
      <webElementGuid>87aa923e-7c9e-48e4-b912-5f0c5ec007e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Special-offer</value>
      <webElementGuid>97cf6a19-71c4-4548-b32a-7fb430d424c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img-special-offer&quot;)/figure[1]/img[1]</value>
      <webElementGuid>1ddc0483-4377-4210-9be6-0b1df6c3d878</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='img-special-offer']/figure/img</value>
      <webElementGuid>66a1eb61-e464-40f1-9ab5-7752bc6a01c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SPECIAL OFFER'])[2]/following::img[1]</value>
      <webElementGuid>a2eb3b92-b422-45c3-bb6a-91d78d7b2e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop Now'])[5]/following::img[1]</value>
      <webElementGuid>c1743f61-9bfb-40bb-a5b8-07b66ae3722c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXPLORE THE NEW DESIGN'])[1]/preceding::img[1]</value>
      <webElementGuid>ada11945-cc10-481e-bbfe-5eb01d5e6f7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HP Pavilion 15z Touch Laptop'])[1]/preceding::img[1]</value>
      <webElementGuid>6a321faa-5721-4883-9948-ead28111f5d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Special-offer']</value>
      <webElementGuid>50d759bf-c201-4ab7-836b-e981e401610a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/img</value>
      <webElementGuid>ce38a655-eae5-4375-ab4e-ffca9c497e2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'css/images/Special-offer.jpg' and @alt = 'Special-offer']</value>
      <webElementGuid>91453e2e-3086-4aac-95f7-41a5b7ebf60b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
