<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_description</name>
   <tag></tag>
   <elementGuidId>e9584625-119b-44c3-902f-3e49aaf3dd70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div > p.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div-special-offer']/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>60c4e491-d93a-4c92-af7c-55d38a4e77ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>e00bcfbc-3a2d-4e71-a862-3ef32f0afd80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Supremely thin, yet incredibly durable </value>
      <webElementGuid>cf302eb9-1394-4e43-a6ff-2f2a7a3c68dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div-special-offer&quot;)/div[1]/p[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>a09da412-ba0a-475c-910d-cd06528a8348</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-special-offer']/div/p</value>
      <webElementGuid>c06df638-15a2-4597-b655-23356cef262d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HP Pavilion 15z Touch Laptop'])[1]/following::p[1]</value>
      <webElementGuid>7bf33963-3c58-4f1d-acef-e3bfbf2d0508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXPLORE THE NEW DESIGN'])[1]/following::p[1]</value>
      <webElementGuid>4c8ba196-2bc2-4735-af20-b1a809a354f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEE OFFER'])[1]/preceding::p[1]</value>
      <webElementGuid>ffc72c6a-a5dd-49f5-8332-8244d179d0a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALL YOU WANT FROM A TABLET'])[1]/preceding::p[1]</value>
      <webElementGuid>850654a0-804c-4e7d-861c-aa534005ef20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p</value>
      <webElementGuid>4218c90d-b038-4178-b14f-a69dde8c9a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = ' Supremely thin, yet incredibly durable ' or . = ' Supremely thin, yet incredibly durable ')]</value>
      <webElementGuid>88eedc78-2ee7-4ea6-9621-34d00c1d45a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
